# AUTO-GENERATED by AVGBuilder V0.2b.
# Source: tools_data/hotspots.json
# Do not edit by hand unless you know what you are doing.

screen hotspots_scene_bg_room_rainy():
    # background: game/images/bg/bg_room_rainy.png
    # hotspot: hotspot_001 | new hotspot
    # tooltip: test tip
    imagebutton:
        idle Solid("#00000000")
        hover Solid("#FFD96655")
        xpos 30
        ypos 40
        xsize 120
        ysize 90
        action Jump("test_label")

    # hotspot: hotspot_002 | new hotspot copy
    # tooltip: test tip
    imagebutton:
        idle Solid("#00000000")
        hover Solid("#FFD96655")
        xpos 50
        ypos 60
        xsize 120
        ysize 90
        action Jump("test_label")
